name: Setup NPM Packages
description: Setup required NPM packages with caching for pnpm and Cypress
runs:
  using: composite
  steps:
    # Cache pnpm store
    - name: Cache pnpm store
      uses: actions/cache@v4.3.0
      with:
        path: ~/.local/share/pnpm/store/v4
        key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-${{ runner.os }}-

    - name: Install NPM packages
      run: |
        pnpm install
      shell: bash
