import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  fluentApi: [{ type: 'autogenerated', dirName: 'fluent-api' }],
};

export default sidebars;
